# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5c9fde6131ad1c05dd798bc8387a551a57b1c1c5afd4c0d74b0cb9e976538ef43db9b6f81bafc539840457e9a9d8b199522430c4ae1b97ccb6c81e90265f13

test:
  secret_key_base: db0b649729d8a7b5c8da4775772eb0754a40b969bc061b2bce2fb4097d956e8ba4316f61cb6cbc82dbf85279dfa71c759979be1be1894474d265a7a80ecf3eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
